### PR TITLE
Clarify clang-format message in CMake

### PR DESCRIPTION
**Pull request by rengolin**
@advancedwebdeveloper, is that clearer from our side?

### CODE REVIEW

**Comment by advancedwebdeveloper** [comment]
That's better - but I was considering that you would explain details of issues with the latest version of clang-format (what is blocking your day-to-day usage).

**Comment by rengolin** [comment]
> That's better - but I was considering that you would explain details of issues with the latest version of clang-format (what is blocking your day-to-day usage).

That's probably better as an email to the mailing list. I can do that, too.

**Review by mjp41 — APPROVED** [review]
LGTM

**Comment by advancedwebdeveloper** [comment]
> > That's better - but I was considering that you would explain details of issues with the latest version of clang-format (what is blocking your day-to-day usage).
> 
> That's probably better as an email to the mailing list. I can do that, too.

Thanks, please share a link to an emailed issue

**Pull request merged**
