### PR TITLE
Add a diagnostic handler for prettier error messages.

### PR DESCRIPTION
**Pull request by plietar**
This gives us a bit of colour, prints the relevant piece of code, and
displays notes attached to diagnostics.

### CODE REVIEW

**Comment by rengolin** [comment]
Nice! How does this interoperate with `main`'s `InitLLVM`? Is it a replacement for that initialisation, or is that still required?

**Comment by mjp41** [comment]
Does this give colour error messages on Windows?  For the prototype I implemented 
  
  https://github.com/microsoft/verona/blob/master/src/ds/console.h

to set the appropriate state for the console on Windows.

**Comment by plietar** [comment]
> How does this interoperate with main's InitLLVM? Is it a replacement for that initialisation, or is that still required?

I think they are orthogonal. `InitLLVM` seems to be (among other things) about catching aborts and segfaults, whereas the diagnostic handler is for all the MLIR `emitError` calls.

`mlir-ops` does both, it calls `InitLLVM` in `mlir-opt.cpp` and sets up a diagnostic handler in `MlirOptMain.cpp`.

**Comment by plietar** [comment]
> Does this give colour error messages on Windows?

I don't really know to be honest. A quick look through the llvm code base, it seems like it ends up relying on stuff in `llvm/lib/Support/Windows/Process.inc`, where colours are set by calling native Windows APIs (rather than emitting ANSI code).
It seems like it might "just work", or at least work as well as llvm and clang do.

Would you mind giving it a try @mjp41? You can pass `verona-mlir` a garbage file like:
```
module {
  abc
}
```

I get this output (notice `error` is in red, and the error message is in bold):

Screenshot 2020-08-07 at 15 11 23

**Pull request merged**
