### PR TITLE
Parse more common string representation

### PR DESCRIPTION
**Pull request by Theodus**
Change string syntax from `` `(...)`` to `"..."`, including common escape
sequences.

### CODE REVIEW

**Comment by sylvanc** [comment]
Let's not merge this until we have an in-depth discussion on string literal representation.

**Comment by Theodus** [comment]
In that case, we should also discuss pattern matching

**Comment by rengolin** [comment]
We could enhance the discussion with explicit tests, as proposed in #120

**Comment by Theodus** [comment]
Closing for now

**Pull request closed without merging**
