### PR TITLE
Fix gcc warnings

### PR DESCRIPTION
**Pull request by Theodus**
Workaround for gcc bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95975

### CODE REVIEW

**Comment by rengolin** [comment]
There's another warning on GCC: `-Werror=unused-but-set-parameter` on `static void gc_notified(Object* o)` and `static void gc_final(Object* o, Object* region, ObjectStack& sub_regions)`.

I know they're not related, but we could probably fix all warnings in one go and get a green build.

**Comment by rengolin** [comment]
best to update both ci and nightly to gcc-10. If we want more coverage, we can create more jobs in the nightly one with different versions, but I don't think that'd be necessary right now.

**Comment by Theodus** [comment]
Everything compiles now, but it seems that there are many runtime errors in the gcc builds.

**Comment by Theodus** [comment]
I think fixing those should be out of the scope for this PR.

**Comment by rengolin** [comment]
It does, but we cannot merge without the main test passing. :(

**Comment by Theodus** [comment]
Welp. I guess I'll be looking into it tomorrow

**Comment by rengolin** [comment]
It was working as of last week, so it's not something that has never worked before... I think a quick bisect could show you the culprit.

But yeah, tomorrow is fine. :)

**Comment by Theodus** [comment]
Closing. See #165

**Pull request closed without merging**
